import express from "express";
import fs from "fs";
import { sequelize } from "./config/db.js";
import initModels from "./models/init-models.js";

const app = express();
app.use(express.json());

// Initialize models ONLY
initModels(sequelize);

// Auto‑mount all routes generated by AutoCRUD
const routesPath = "./routes";

fs.readdirSync(routesPath)
  .filter(file => file.endsWith("Routes.js"))
  .forEach(file => {
    const route = file.replace("Routes.js", "");
    import(`./routes/${file}`).then(module => {
      app.use(`/api/${route}`, module.default);
    });
  });

const PORT = 3000;
app.listen(PORT, () =>
  console.log(`Servidor en http://localhost:${PORT}`)
);
