import express from "express";
import fs from "fs";
import path from "path";
import { sequelize } from "./config/db.js";

const app = express();
app.use(express.json());

const routesPath = "./routes";

// Auto‑mount all routes generated by AutoCRUD
fs.readdirSync(routesPath)
  .filter(file => file.endsWith("Routes.js"))
  .forEach(file => {
    const route = file.replace("Routes.js", "");
    import(`./routes/${file}`).then(module => {
      app.use(`/api/${route}`, module.default);
    });
  });

(async () => {
  try {
    await sequelize.sync({ alter: true });
    console.log("Tablas sincronizadas.");
  } catch (error) {
    console.error("Error al sincronizar las tablas:", error);
  }
})();

const PORT = 3000;
app.listen(PORT, () =>
  console.log(`Servidor en http://localhost:${PORT}`)
);
